app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

server:
  forward-headers-strategy: framework

spring:
  application:
    name: "NomNomNowBackend"
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  security:
    oauth2:
      client:
        registration:
            google:
                client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
                client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
                scope: openid, profile, email
