CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION nnn_owner;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nnn_app') THEN

CREATE ROLE nnn_app LOGIN PASSWORD '${appUserPassword}';
END IF;
END$$;

GRANT USAGE ON SCHEMA app TO nnn_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA app
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nnn_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA app
    GRANT USAGE, SELECT ON SEQUENCES TO nnn_app;

CREATE TABLE IF NOT EXISTS app.category (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);