name: backendCi.yml
on:
  pull_request:
    branches:
      - "main"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build & Test Backend
        run: mvn -B -DskipTests=false verify
