name: backendCd.yml

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        id: bx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Show buildx builders
        run: docker buildx ls

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build (Maven)
        run: mvn -B -DskipTests package

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive image/cache names (lowercase)
        id: repo
        run: |
          REPO="${GITHUB_REPOSITORY}"
          IMG="${{ env.REGISTRY }}/${REPO,,}"
          echo "image=$IMG" >> "$GITHUB_OUTPUT"
          echo "cache=$IMG:buildcache" >> "$GITHUB_OUTPUT"

      - name: Get short SHA
        id: meta
        run: echo "sha_tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.bx.outputs.name }}
          context: .
          push: true
          tags: |
            ${{ steps.repo.outputs.image }}:latest
            ${{ steps.repo.outputs.image }}:${{ steps.meta.outputs.sha_tag }}
          cache-from: type=registry,ref=${{ steps.repo.outputs.cache }}
          cache-to: type=registry,ref=${{ steps.repo.outputs.cache }},mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Copy compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml"
          target: ${{ secrets.APP_DIR }}
          overwrite: true
          strip_components: 0

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: GITHUB_TOKEN,GITHUB_ACTOR
          script: |
            set -euo pipefail
            cd "${{ secrets.APP_DIR }}"

            # Login an GHCR mit dem kurzlebigen Workflow-Token (nur für diesen Pull)
            echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin || true

            if [ -f docker-compose.prod.yml ]; then
              export COMPOSE_FILE=docker-compose.yml:docker-compose.prod.yml
            else
              export COMPOSE_FILE=docker-compose.yml
            fi

            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
